version: "3"

networks:
  default:
    external:
      name: adonis-app

services:
  app:
    build:
      context: ./docker/node
    user: "node"
    command: bash -c 'adonis serve --dev'
    restart: always
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    environment:
      PORT: 3333
      HOST: 0.0.0.0
      DB_HOST: db
      DB_USER: adonis
      DB_PORT: 5432
      DB_PASSWORD: adonis
      DB_DATABASE: adonis
      DB_CONNECTION: pg
      REDIS_HOST: redis

  nginx:
    build:
      context: ./docker/nginx
    restart: always
    depends_on:
      - app
    ports:
      - 3333:80
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/config/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./:/var/www

  db:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_DB: adonis
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: welkome
    ports:
      - 5444:5432
    volumes:
      - ./var/postgresql:/var/lib/postgresql

  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - ./var/redis:/data
